---
trigger:
- main

pool:
  name: react-pool

jobs:
- job: BuildAndDeployReactApp
  displayName: 'Build and Deploy React App'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm run build
    displayName: 'Build React App'

  - task: CopyFiles@2
    inputs:
      contents:
        dist/**  # Adjust this based on your React app's build output
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'ReactApp'

  # Add deployment steps according to your deployment strategy
